services:
  db:
    image: postgres:17
    container_name: postgres-db-jpa
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: java-jpa-app
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata: